apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-hello
  labels:
    app: node-hello
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-hello
  template:
    metadata:
      labels:
        app: node-hello
    spec:
      containers:
      - name: node-hello
        image: 559050232518.dkr.ecr.us-east-2.amazonaws.com/demo-ecr-repo:{{IMAGE_TAG}} # Replace with your ECR repo URI
        ports:
        - containerPort: 6000
