apiVersion: v1
kind: Service
metadata:
  name: node-hello-service
spec:
  type: NodePort
  selector:
    app: node-hello
  ports:
  - protocol: TCP
    port: 80               # The port the service will expose internally
    targetPort: 6000       # The container port the service routes traffic to
    nodePort: 30001         # The fixed NodePort to expose externally (between 30000–32767)
