apiVersion: v1
kind: Service
metadata:
  name: node-hello-service
spec:
  type: ClusterIP           # Change type to ClusterIP
  selector:
    app: node-hello
  ports:
  - protocol: TCP
    port: 6000               # The port the service will expose internally
    targetPort: 6000       # The container port the service routes traffic to
