apiVersion: v1
kind: Service
metadata:
  name: node-hello-service
spec:
  type: LoadBalancer         # Change type to LoadBalancer
  selector:
    app: node-hello
  ports:
  - protocol: TCP
    port: 6000               # The port the service will expose externally
    targetPort: 6000
